version: '3.1'

services:

  wordpress:
    image: wordpress:5.7.2-php7.4-apache
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - ./evercate-signup-wordpress-plugin/:/var/www/html/wp-content/plugins/evercate-signup-wordpress-plugin

  db:
    image: mariadb:10.3.29
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

volumes:
  wordpress:
  db: